# Site settings
title: Luctor et Emergen
email: leon@solatis.com
seo_descr: > 
  Random thoughts and ramblings about engineering, Haskell, philosphy and
  living a good life.
seo_keywords: "leon mergen, haskell"
baseurl: ""
url: "http://www.leonmergen.com" # the base hostname & protocol for your site
twitter_username: solatis
github_username:  solatis

# Build settings
markdown: kramdown
