# Site settings
title: Eo ipso
email: leon@solatis.com
description: > # this means to ignore newlines until "baseurl:"
  Random thoughts and ramblings about engineering, Haskell, philosphy and
  living a good life.
baseurl: ""
url: "http://www.leonmergen.com" # the base hostname & protocol for your site
twitter_username: solatis
github_username:  solatis

# Build settings
markdown: kramdown
